### ISSUE TITLE
Flipper Sniff PMKID ap and Sniff <pmkid>

### ISSUE THREAD

**Issue by ncsu201** [0xchocolate/flipperzero-wifi-marauder#15]
### Describe the bug.

When using the Sniff PMKID ap option on the Flipper the majority of packets captured, including EAPOLS, are not from the targeted ap.

I'm also wondering, what's the difference between using the Sniff option with <pmkid> selected and using Sniff PMKID option right below it with ap selected? The only thing I can tell is that the Sniff PMKID ap option also sends deauths, if you have that setting enabled, while the Sniff <pmkid> option does not.

Also, I thought one of the main advantages of the newer PMKID attack was that it doesn't require deauths, or even any connected clients at all, it sends an association request to grab the PMKID straight from the AP. So why does the Sniff PMKID option send deauths at all? It seems to be sending deauths and trying to grab the hash at the EAPOL stage, which is not a PMKID attack as the name of the option on the Flipper would imply.

### Reproduction

Simply run Sniff PMKID ap

**Comment by 0xchocolate** [comment]
Is this a marauder fw issue or an app issue? If the app is sending the correct commands, then this is a marauder fw issue.

**Comment by ncsu201** [comment]
For the Sniff <pkmid> option it's using sniffpkmid without any arguments.
For the Sniff PKMID option below it it's using sniffpkmid -d -l so both
sending deauths and targeting only selected APs. What I don't know, because
the marauder wiki doesn't clarify, is whether the -l is directing the
deauths or the sniff to only target the selected APs. What is the intended
purpose behind having two redundant Sniff PKMID options in the list that
both behave slightly differently?

**Comment by 0xchocolate** [comment]
"-d" is for deauth, "-l" is to use the list.

**Comment by 0xchocolate** [comment]
There's now an issue for this in the marauder fw repo, so I'm closing this: https://github.com/justcallmekoko/ESP32Marauder/issues/267

**Comment by jjoshm** [comment]
It is possible to disable the deauth by setting the ForcePMKID to disable in the settings
