### ISSUE TITLE
Flipper Zero crash when restarting plugin after rickroll attack.

### ISSUE THREAD

**Issue by gravityfox** [0xchocolate/flipperzero-wifi-marauder#2]
If I open the plugin, start the rickroll attack, stop the attack, exit the app, and then restart the app again, the flipper crashes and restarts due to "NULL pointer dereference".

Tested on Eng1n33r's Unleashed firmware, build un1-12a629.

**Comment by 0xchocolate** [comment]
Fixed in v0.2.2 :)
