### ISSUE TITLE
How to Edit ? (if possible)

### ISSUE THREAD

**Issue by Dieudumonde** [0xchocolate/flipperzero-wifi-marauder#21]
Hey,

I just wanted if it was possible to edit the ESP32_WiFi_Marauder.fap file to change the rickroll by anything else ?

**Comment by 0xchocolate** [comment]
Watch this video and pay attention to how to execute a beacon attack with an ssid list: https://youtu.be/YpVu-UF6k10

If that doesn't help, look through the marauder wiki or ask on discord.

**Comment by Dieudumonde** [comment]
thank you ! but i don't have all the same options like in the video, i don't have the scripts option for exemple, i just have to update the marauder or i have to add it by myself ?

**Comment by 0xchocolate** [comment]
Update the app

**Comment by Dieudumonde** [comment]
where is the new ESP32_Wifi_Marauder.fap file ? because the "problem" comes from this file i think

edit : i just had to update the unleashed frimware lol sorry
