### ISSUE TITLE
sniffing during the deauth attack performing

### ISSUE THREAD

**Issue by maloleg** [0xchocolate/flipperzero-wifi-marauder#24]
Hey everyone!

Is it possible to perform a deauth attack while sniffing to save pcaps with handshakes on sd card? Maybe i am wrong, but as i understand its not possible in the latest fw.

**Comment by 0xchocolate** [comment]
Are you using sniffpmkid? The "active" option is supposed to do this.

**Comment by maloleg** [comment]
Oh, yeah, now I get it, appreciate that!
