### ISSUE TITLE
Unsure where to place Evil Portal index.html and ap.config.txt

### ISSUE THREAD

**Issue by SunnySkye** [0xchocolate/flipperzero-wifi-marauder#28]
Hi there
This could just be me being a bit dense.
But I when I go to use the Evil Portal function in the ESP32 Marauder application, it says that it can't find /index.html.

![Screenshot-20230904-193246](https://github.com/0xchocolate/flipperzero-wifi-marauder/assets/91105990/f1bf77d4-6047-42f0-a48d-2cb90c5af462)

I have sample files ready to go, but I am just not sure where to place them.

**Comment by bitterbuick** [comment]
Check out the instructions on the fork here: https://github.com/justcallmekoko/ESP32Marauder/wiki/evil-portal-workflow

Edit: better yet, specifically here: https://github.com/justcallmekoko/ESP32Marauder/wiki/evilportal

**Comment by Hillehom** [comment]
- nazwa: Zbuduj pakiet aplikacji płetwy ( .fap )
                wykorzystuje: flipperdevices / flipperzero-ufbt-action @ v0.1.2

**Comment by opskovitch** [comment]
I am encountering the exact same issue, and tried copying the `index.html` file at various locations on the Flipper Micro SD card, at:
- /index.html
- /apps_data/index.html
- /apps_data/marauder/index.html

None of these seem to work, error persists.

Then I noticed I initially missed an important note in docs: https://github.com/justcallmekoko/ESP32Marauder/wiki/evil-portal-workflow#important-note

Not very experienced on the topic but could it be that `/apps_data/marauder/ap.config.txt` is read from the Flipper Zero SD Card, while `/index.html` is read from the root of the ESP32 SD Card ? 

Note: That would require extra hardware enabling the ESP32 SD card capabilities, using either a [SD adapter](https://www.tindie.com/products/justcallmekoko/wifi-dev-board-micro-sd-adapter/) board or a [MicroSD Breakout](https://www.sparkfun.com/products/544) according to the following instructions: https://github.com/justcallmekoko/ESP32Marauder/wiki/flipper-zero#sd-card-modification

@bitterbuick did I get this right ?

**Comment by Sonkeiseven** [comment]
Bonjour, j'ai réussi en suivant cette vidéo : https://www.youtube.com/watch?v=ktIvzB__pTs

et ce github : https://github.com/bigbrodude6119/flipper-zero-evil-portal#erasing-firmware

**Comment by ssshake** [comment]
I think the confusing here might be the same I'm encountering. I just flashed the Marauder firmware using the online tool (https://fzeeflasher.github.io/).

Then I installed this application through the flipper labs website. 

Inside of this app there is an option to start evil portal. It just seems to hang. 

Some documentation says to put index.html and ap.config.txt in the root of the sd card on the ESP32 device (mine does not have an sd card slot, it's the official flipper wifi dev board).

Other instructions say to put these files into /app_datas/evil_portal (which didn't exist).

Neither work.

It seems that evil portal can be its own stand alone firmware, or baked into marauder. 

It seems that there may be a stand alone evil portal app?(confused).

So it's just confusing which instructions to refer to.

Can the Marauder firmware, on a wifi dev board with no SD card, access index.html and ap.config.txt from the SD card on the flipper itself? If so where and how?

Selecting Update SD in this app's interface says SD support is disabled. Not sure what to make of it. Any help would be appreciated.

**Comment by 0xchocolate** [comment]
As of Marauder FW v0.13.5 and app version v0.6.5:
If your esp32 board doesn't have an sd card, then use the new option in the app to load HTML to Evil Portal. It will open a file browser for you to select the file from the flipper sd card, then it will send the file contents to the esp32. Make sure you also have an ap and/or ssid selected from their respective lists (you can add your own ssid by name). Then start the portal.

**Comment by opskovitch** [comment]
@0xchocolate amazing thanks, will try and confirm once it works

**Comment by ATKellett04** [comment]
> As of Marauder FW v0.13.5 and app version v0.6.5: If your esp32 board doesn't have an sd card, then use the new option in the app to load HTML to Evil Portal. It will open a file browser for you to select the file from the flipper sd card, then it will send the file contents to the esp32. Make sure you also have an ap and/or ssid selected from their respective lists (you can add your own ssid by name). Then start the portal.

I have the Marauder FW v0.13.5 and app version v0.6.5 but when I load the html file nothing changes and the portal still says 'could not find /index.html'

Any ideas?
Thanks

**Comment by 0xchocolate** [comment]
Please provide the following logs:

1. Boot log from starting up (to verify the version)
2. After loading html
3. After starting Evil Portal

@ATKellett04

**Comment by ATKellett04** [comment]
@0xchocolate Apologies, unsure about getting a boot log but here are the others
[evilportal_0.log](https://github.com/0xchocolate/flipperzero-wifi-marauder/files/13540097/evilportal_0.log)
[evilportal_1.log](https://github.com/0xchocolate/flipperzero-wifi-marauder/files/13540101/evilportal_1.log)

Thanks

**Comment by 0xchocolate** [comment]
Is this a published portal (known to work) or your own file? Could you provide the html file?

**Comment by 0xchocolate** [comment]
Also, does it always fail? Have you tried retrying and/or resetting?

**Comment by ATKellett04** [comment]
Yeah its a public html but i've tweak a couple things but only text so it has no reason not to work, and yeah Ive reset the board a couple times, i've even reloaded the companion app and the firmware and always seems to fail :/ being a pain in my bum

**Comment by m00nyONE** [comment]
> As of Marauder FW v0.13.5 and app version v0.6.5: If your esp32 board doesn't have an sd card, then use the new option in the app to load HTML to Evil Portal. It will open a file browser for you to select the file from the flipper sd card, then it will send the file contents to the esp32. Make sure you also have an ap and/or ssid selected from their respective lists (you can add your own ssid by name). Then start the portal.

Is there a way to use this as a script? I can't get it to work sadly.

i have a script like this:
`
ssid -a -n TestPortal
evilportal -c sethtml portals/testportal.html
evilportal -c start
`

the template works and is tested.
But it seems like the upload of the html is via serial? so how do i send it over as a command ?
