### ISSUE TITLE
bluetooth attack not supported by esp32-s3-1u module

### ISSUE THREAD

**Issue by LuckyFishGeek** [0xchocolate/flipperzero-wifi-marauder#35]
ESP32Marauder:  esp32_marauder_v0_13_1_20231014_multiboardS3.bin

flipperzero-wifi-marauder: v0.6.3

![QQ图片20231015082235](https://github.com/0xchocolate/flipperzero-wifi-marauder/assets/29472751/b87f5cea-3193-4949-94ca-de496fab75c5)

**Comment by Tags1021** [comment]
Did you find a work around for this issue?
