### ISSUE TITLE
Nothing happens when anything is selected

### ISSUE THREAD

**Issue by icantcodeswiftforshit** [0xchocolate/flipperzero-wifi-marauder#38]
- it's probably because i did it wrong
- whenever i click anything in the menu, all it says is-
Press BACK to send stopscan
- help

**Comment by Crashinsane** [comment]
> - it's probably because i did it wrong
> - whenever i click anything in the menu, all it says is-
> Press BACK to send stopscan
> - help

**Comment by icantcodeswiftforshit** [comment]
i forgor to install boot loader. am going to kill self in 6.7 minutes
