### ISSUE TITLE
Flashing Issue on LDDB

### ISSUE THREAD

**Issue by supermicaiah** [0xchocolate/flipperzero-wifi-marauder#39]
For some reason when I flash the fw for LDDB marauder doesn't work. I am using the esp flasher app on the flipper

**Comment by 0xchocolate** [comment]
What file are you using?

**Comment by KosmikSinge** [comment]
i purchased a LDDB and it isnt registering the FW. ive followed every guide i can find but it keeps telling me to put it in bootloader but ive done it. im lost right now
