### ISSUE TITLE
Add new Marauder CLI commands from v0.9.16, v0.9.17

### ISSUE THREAD

**Issue by justcallmekoko** [0xchocolate/flipperzero-wifi-marauder#4]
### Integrate:

command: `sniffraw`
description:
Sniff raw WiFi traffic including data frames. Outputs source MAC address to display

### Modify:

command: `attack -t deauth [-s <src_addr>] [-d <dst_addr>]`
description:
Users will have the option to specify a source MAC address and/or a destination MAC address when executing a deauthentication attack. If the user wishes to specify an address, they will be expected to format it as follows...
`xx:xx:xx:xx:xx:xx` or `XX:XX:XX:XX:XX:XX`. All other functionality of the attack command remains unchanged

**Comment by 0xchocolate** [comment]
First part done. Second part will take a bit longer.

**Comment by 0xchocolate** [comment]
Implemented manual deauth in latest release. Please test it!
