### ISSUE TITLE
Wifi DevBoard installation does not work

### ISSUE THREAD

**Issue by tuxsaporo** [0xchocolate/flipperzero-wifi-marauder#46]
I'm trying to install the Marauder firmware on my Flipper dev board, and even after the binary has been flashed, a red light appears after boot.
I tried to install it several times, but there was no success.

**Comment by 0xchocolate** [comment]
How are you flashing it? (Which process are you using?)

Have you tried any of the app functions? Is this an issue with this app?

**Comment by tuxsaporo** [comment]
I've tried using the FZEaztMarauderFlash.
Even after the reset button is pressed, I see the red light.

![IMG_0117](https://github.com/0xchocolate/flipperzero-wifi-marauder/assets/100784790/b1bfbdc1-95c1-4490-8190-e4230d96571e)


https://github.com/0xchocolate/flipperzero-wifi-marauder/assets/100784790/b77efca9-97f0-44d8-bced-aae13424f68d

**Comment by 0xchocolate** [comment]
Okay? What happens if you try to scan?

**Comment by tuxsaporo** [comment]
Nothing. 
It's like the ESP cannot boot the firmware.

**Comment by 0xchocolate** [comment]
That LED sequence (blue -> green -> red) is indeed marauder fw booting up.

I don't know what you're having trouble with.

**Comment by tuxsaporo** [comment]
I'll try again.
Maybe there is a problem with my board.
Thank you so much.

**Comment by 0xchocolate** [comment]
I don't think there's a problem with your board - it's clearly flashed...
