### ISSUE TITLE
Evil Twin attacks with the ESP32?

### ISSUE THREAD

**Issue by sealldeveloper** [0xchocolate/flipperzero-wifi-marauder#5]
### Description of the feature you're suggesting.

This would be a helpful feature to utilize.

### Anything else?

Love the program!

**Comment by 0xchocolate** [comment]
Is this a request for marauder FW? You might want to file it on that project instead. Please also describe exactly what you want the feature to do.

**Comment by sealldeveloper** [comment]
Oh, apologies.

The feature is for an SSID to be replicated and created as a new network, and then to simultaneously deauth attack the network with the same name.

Eg.
Deauth a WiFi with the SSID "Example Wifi"
Create a new, passwordless network with the SSID "Example Wifi"
Devices would connect to the new created network instead of the real "Example Wifi"

**Comment by sealldeveloper** [comment]
https://wikiless.org/wiki/Evil_twin_(wireless_networks)
