### ISSUE TITLE
App Too New APP:72 > FW:54

### ISSUE THREAD

**Issue by HuJ2kgv** [0xchocolate/flipperzero-wifi-marauder#59]
Is my firmware out of date? This is the Xtreme-flipper Firmware and I want to keep it
When I try selecting an AP it crashes and reboots
Which version should I get?

**Comment by HuJ2kgv** [comment]
**Flipper crashed but has rebooted**

NULL pointer dereference

**Comment by 0xchocolate** [comment]
Not sure what you're expecting here.

It's time to move on.
