### ISSUE TITLE
Error: Outdated App

### ISSUE THREAD

**Issue by a1exus** [0xchocolate/flipperzero-wifi-marauder#60]
Hello,

I grabbed [latest](https://github.com/0xchocolate/flipperzero-wifi-marauder/actions/workflows/build.yml), more specifically [flipperzero-wifi-marauder-f7-api-72.1-0.105.0](https://github.com/0xchocolate/flipperzero-wifi-marauder/actions/runs/10784527304) file, copy it to `SD Card/apps/GPIO` and then tried to run it, however i'm getting the following error when i try to run it

> Error: Outdated App

Please advise)
Thanks!

**Comment by 0xchocolate** [comment]
On which flipper FW version?

**Comment by a1exus** [comment]
> On which flipper FW version?

Product: Flipper Zero
Model: FZ.1
FW: DEV 5F4F4FCC

**Comment by 0xchocolate** [comment]
Did you try grabbing the corresponding app build: flipperzero-wifi-marauder-f7-api-73.0-5f4f4fcc

**Comment by a1exus** [comment]
> Did you try grabbing the corresponding app build: flipperzero-wifi-marauder-f7-api-73.0-5f4f4fcc

i obviously did not ;p, thank you for point this out for me))
